pool:
  name: vs2017-win2016

pr:
  batch: true
  branches:
    include:
    - develop
    - master

trigger:
  batch: true
  branches:
    include:
    - develop
    - master

variables:
  BuildConfiguration: release

steps:
  - task: gittools.gitversion.gitversion-task.GitVersion@5
    displayName: GitVersion
    inputs:
      preferBundledVersion: false
  
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(Parameters.RestoreBuildProjects)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(Parameters.RestoreBuildProjects)'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Run only non mutating tests'
    inputs:
      command: test
      projects: '**/*[Tt]est?(s).csproj'
      arguments: '--configuration $(BuildConfiguration) --filter TestCollection!=Crud -- xunit.maxParallelThreads=1'
  
  - task: DotNetCoreCLI@2
    displayName: 'Run only mutating tests'
    inputs:
      command: test
      projects: '**/*[Tt]est?(s).csproj'
      arguments: '--configuration $(BuildConfiguration) --filter TestCollection=Crud -- xunit.parallelizeTestCollections=false'
  
  - task: DotNetCoreCLI@2
    displayName: 'Pack for nuget'
    inputs:
      command: pack
      packagesToPack: '**/*!([Tt]est?(s)).csproj'
      nobuild: true
      versioningScheme: byEnvVar
      versionEnvVar: GitVersion.NuGetVersion
  
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '**/*.nupkg;!**/*.symbols.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: 'NKovacic Nuget API'
      
      